name: 'Export all variables from secrets and vars contexts to env variables'
description: 'Utility action that exports all github secrets and vars to environment variables'
author: 'Danilo Körber'
inputs:
  secrets:
    required: false
    description: JSON representation of the secrets, use provided placeholder'
  vars:
    required: false
    description: JSON representation of the vars, use provided placeholder'
  prefix:
    required: false
    description: 'Prefix to add to all secrets, e.g.: SECRET_'
  suffix:
    required: false
    description: 'Suffix to add to all secrets, e.g.: _SECRET'
  only:
    required: false
    description: 'Comma-separated list of secrets to export'
  except:
    required: false
    description: 'Comma-separated list of secrets to skip exporting'
  transform:
    required: false
    description: 'Converts secrets name to a specific string format'
  transformPrefix:
    required: false
    description: 'Include prefix (or not) on conversion. True by default'
  transformSuffix:
    required: false
    description: 'Include suffix (or not) on conversion. True by default'
  override:
    required: false
    description: 'Either to override or not the variable if it already exists'
  convert:
    required: false
    description: 'Either to convert the value to base64 or utf8'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: shield
  color: orange
